// Natura Vida 10.1.5: el numero de cuotas no se reescribe mientras se edita.
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const src=fs.readFileSync(path.join(root,'js/v8-financial-accounts.js'),'utf8');
const version=JSON.parse(fs.readFileSync(path.join(root,'app-version.json'),'utf8'));
assert.equal(version.version,'10.1.5');
const start=src.indexOf('      const scheduleNow=()=>{');
const end=src.indexOf('      const refresh=()=>{',start);
assert(start>0&&end>start,'El calculador de cuotas debe poder evaluarse');
const count={value:'1'},mode={value:'count'},amount={value:'100'},frequency={value:'monthly'},first={value:'2026-10-16'};
const scheduleBuilder=(total,n,date,period)=>Array.from({length:n},(_,i)=>({number:i+1,amount:total/n,dueDate:date+i*86400000,frequency:period}));
const schedule=new Function('first','defaultDate','count','mode','amount','frequency','account','buildPaymentScheduleV820',src.slice(start,end)+'\nreturn scheduleNow;')(first,'2026-10-16',count,mode,amount,frequency,{totalDebt:1200},scheduleBuilder);
assert.equal(schedule().length,1);
count.value='';
assert.throws(()=>schedule(),/Escribe el número de cuotas/);
assert.equal(count.value,'','El campo debe seguir vacio tras borrar el 1');
count.value='2';
assert.equal(schedule().length,2);
assert.equal(count.value,'2','No debe sobrescribirse el valor introducido');
count.value='24';
assert.equal(schedule().length,24);
count.value='121';
assert.throws(()=>schedule(),/entero entre 1 y 120/);
assert.equal(count.value,'121','No se debe corregir mientras se escribe');
count.value='1.5';
assert.throws(()=>schedule(),/entero entre 1 y 120/);
mode.value='amount';amount.value='150';
assert.equal(schedule().length,8);
assert.equal(String(count.value),'8','Modo monto sí puede rellenar el número derivado');
assert(src.includes("await syncGenericCloudStoreToLocalV9('paymentPlans');"),'Sincronizar antes de abrir y guardar');
assert(src.includes('const activeNow=activePaymentPlanV825(clientId)'),'Consultar el plan vigente antes de reemplazar');
assert(src.includes("existingIdToReplace=String(activeNow.id)"),'Enviar a Supabase el plan vigente a reemplazar');
assert(src.includes('¿Reemplazar ese cronograma por'),'Solicitar autorización explícita');
assert(src.includes('replacePaymentPlanAtomicV9(plan,existingIdToReplace)'),'Nunca insertar plan extra sin pasar su identificador previo');
assert(src.includes('El plan activo pertenece a otra cuenta'),'Respetar propietario del plan');
assert(src.includes('const savedSchedule=Array.isArray(savedPlan.schedule)'),'Los documentos deben usar el cronograma confirmado');
assert(!src.includes("Math.trunc(c)||1"),'No reinstaurar automáticamente el 1 en modo número');
console.log('OK V10.1.5: campo vaciable, conteo 2/24, validación, plan vigente y reemplazo autorizado.');
