// Regression V10.1.4 — importacion historica desde respaldo privado, sin clientes reales.
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'js/v8-financial-accounts.js'),'utf8');
const Core=require('../js/v8-financial-core.js');
const found=source.match(/  function parseCsvV820\(text\)\{[\s\S]*?\n  \}/);
assert(found,'Parser CSV histórico inexistente');
const parseCsv=new Function('norm',found[0]+'\nreturn parseCsvV820;')(Core.norm);
const sample='cliente;fecha;numero_venta;productos;total_venta;pagado;saldo_pendiente;observaciones\nCliente Ficticio;20/07/2026;DEMO-1;Aceite de prueba;500;100;400;Prueba';
const csv=parseCsv(sample);
assert.equal(csv.length,1);
assert.equal(csv[0].clientName,'Cliente Ficticio');
assert.equal(csv[0].total,500);
assert.equal(csv[0].balance,400);
const row=Core.normalizeHistoricalRow(csv[0]);
assert.equal(row.clientName,'Cliente Ficticio');
assert.equal(row.pendingBalance,400);
assert.equal(row.inventoryImpact,false,'Importacion historica nunca debe afectar inventario');
assert.equal(row.historicalActive,true);
assert(source.includes("const feedback=$('#nv820ImportFeedback',overlay)"),'Falta mensaje permanente en la pantalla');
assert(source.includes("role=\"status\" aria-live=\"polite\""),'Debe existir estado accesible');
assert(source.includes('Primero descarga el respaldo en tu teléfono'),'Explicar por qué el archivo no viene preinstalado');
assert(source.includes('current=[];confirm.disabled=true'),'Una lectura fallida debe impedir confirmación obsoleta');
assert(source.includes('p.normalized.length'),'Debe explicar la cantidad de registros válidos');
assert(source.includes('No hay registros nuevos para importar.'),'Debe avisar sobre duplicados');
assert(source.includes("input.value='';input.click();"),'Permitir escoger otra vez el mismo archivo en Android');
assert(source.includes('No se pudo preparar la vista previa:'),'El error de lectura debe permanecer visible');
assert(!source.includes("fetch('data/imports/"),'Nunca volver a descargar datos personales desde URL publica');
console.log('OK V10.1.4: vista previa Android, CSV sintético, errores y privacidad.');
