// Regresion de incidentes observados en Android PWA V10.1.1 (corregidos V10.1.8)
'use strict';
const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const root=path.resolve(__dirname,'..');
const read=x=>fs.readFileSync(path.join(root,x),'utf8');
const auth=read('js/supabase-sync.js');
const roles=read('js/auth.js');
const mgmt=read('js/v7-management-center.js');
const finance=read('js/v8-financial-accounts.js');
const sw=read('service-worker.js');
const ver=JSON.parse(read('app-version.json'));
assert.equal(ver.version,'10.1.8');
assert(auth.includes("sb.from('profiles').select('id,email,full_name,role,status"),'Se debe consultar el perfil autentico');
assert(!/from\('profiles'\)\.select\('[^']*permissions/.test(auth),'profiles.permissions no existe en PostgreSQL');
assert(roles.includes('permissions: permissionsForRole(commercialRole)'),'Los permisos deben derivarse del rol');
assert(mgmt.includes("action.tab === 'reglas-comerciales'"),'Debe existir acceso dedicado a reglas');
assert(mgmt.includes('await ensureCommercialRulesModuleV9()'),'El acceso debe cargar el modulo antes de navegar');
assert(mgmt.includes("window.navigateTo('reglas-comerciales')"),'Debe abrir el modulo comercial');
assert(finance.includes('Número de cuotas (1 a 120)'),'El formulario debe permitir escoger cuotas');
assert(finance.includes('id="nv820PlanCount" type="number" inputmode="numeric" min="1" max="120"'),'El conteo debe ser editable');
assert(finance.includes('count.value=c;'),'El conteo debe reflejar el valor calculado');
assert(finance.includes('let pendingPlan=null, committedPlan=null, pendingDocumentId=null'),'Reintentos deben conservar plan/documento');
assert(finance.includes('const plan=pendingPlan||{id:uid(\'plan\')'),'No regenerar identificador de plan tras error');
assert(finance.includes('const atomicPlan=committedPlan?'),'No reenviar el plan si ya se guardo');
assert(finance.includes('id:pendingDocumentId,documentType:\'PPA\''),'Evitar documento duplicado al reintentar');
assert(finance.includes('role="alert" aria-live="polite"'),'Errores deben quedar visibles en formulario');
assert(sw.includes('nv-app-shell-v10-1-8') && sw.includes('nv-runtime-v10-1-8'),'La PWA requiere cache nuevo');
console.log('OK: seguridad de acceso, modulo de reglas y conteo / reintento de planes V10.1.8.');
