const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');
const root=path.resolve(__dirname,'..');
const script=fs.readFileSync(path.join(root,'js/v8-ai-assistant.js'),'utf8');
const sql=fs.readFileSync(path.join(root,'supabase/migrations/20260801_v834_ai_control_center.sql'),'utf8');
const version=JSON.parse(fs.readFileSync(path.join(root,'app-version.json'),'utf8'));
assert.equal(version.version,'8.3.5');
for(const token of ['weeklySummaryV835','ensureWeeklySummaryV835','proactiveActionsV835','showProactiveBriefV835','taskGroupsV835','personnelScoreV835','Director Ejecutivo Proactivo'])assert(script.includes(token),token);
for(const token of ['nv_ai_control_tasks','nv_ai_control_state','enable row level security','supabase_realtime','notify pgrst','primary key (owner_user_id,id)'])assert(sql.includes(token),token);
const store=new Map();global.window=global;global.localStorage={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k)};global.document={readyState:'loading',addEventListener(){},querySelectorAll(){return[];},querySelector(){return null;},getElementById(){return null;}};global.navigator={onLine:false};global.CustomEvent=function(){};global.addEventListener=()=>{};global.dispatchEvent=()=>{};
global.AppState={session:{userId:'admin-test'},currentTab:'inicio',products:[],clients:[],sales:[],historicalReceivables:[],receivablePayments:[],settings:{},productionOrders:[]};
vm.runInThisContext(script,{filename:'v8-ai-assistant.js'});
const api=global.__nvAiV835;assert(api,'API V835 no exportada');
global.AppState.products=[{id:'p200',name:'Aceite de Coco 200 ml',stock:0,price:60,cost:22,status:'active'}];
global.AppState.sales=[{id:'s1',date:Date.now(),total:60,items:[{productId:'p200',name:'Aceite de Coco 200 ml',qty:1,price:60,cost:22}]}];
const weekly=api.weeklySummaryV835();assert(weekly.weekStart&&weekly.metrics&&Array.isArray(weekly.facts));assert.equal(weekly.metrics.currentRevenue,60);
const task=api.resolveDraftActionV829('Crea una tarea urgente responsable Gloria para revisar cobranzas hoy',{});assert.equal(task.type,'create_task');assert.equal(task.taskResponsible,'Gloria');
const actions=api.proactiveActionsV835();assert(Array.isArray(actions));assert(actions.some(x=>x.title.includes('producción')||x.title.includes('Producir')));
const evaluation=api.businessEvaluationV832();assert(evaluation.dimensions.some(x=>x.name==='Personal'));
const count=(()=>{let n=0;const walk=d=>fs.readdirSync(d,{withFileTypes:true}).forEach(e=>e.isDirectory()?walk(path.join(d,e.name)):n++);walk(root);return n;})();assert(count<=100,`demasiados archivos: ${count}`);
console.log(`V8.3.5 OK: Director proactivo, resumen semanal, agenda, personal y ${count} archivos.`);
